<?php

namespace AppBundle\Repository;

/**
 * FeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeeRepository extends \Doctrine\ORM\EntityRepository
{
}
