<?php

namespace AppBundle\Repository;

/**
 * FeeScaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeeScaleRepository extends \Doctrine\ORM\EntityRepository
{
}
