<?php

namespace AppBundle\Repository;

/**
 * FeeTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeeTypeRepository extends \Doctrine\ORM\EntityRepository
{
    const PER_MILE = 1;
}
