<?php

namespace AppBundle\Repository;

/**
 * VehicleTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleTypeRepository extends \Doctrine\ORM\EntityRepository
{
    const SMALL_VAN = 1;
    const SWB = 2;
    const SPRINTER_PAY_SWB = 3;
    const SPRINTER = 4;
    const LUTON_OR_CURTAINSIDE = 5;
    const ARCTIC = 6;
    const SPECIAL = 7;
}
